name: Mein Tanita Garmin Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 6'

jobs:
  sync-job:
    runs-on: ubuntu-latest
    steps:
      - name: Code herunterladen
        uses: actions/checkout@v4
      
      - name: Programm bauen (Docker)
        run: docker build -t mein-sync-tool .
        
      - name: Synchronisation ausfuehren
        run: docker run --rm -e GARMIN_EMAIL="${{ secrets.GARMIN_EMAIL }}" -e GARMIN_PASSWORD="${{ secrets.GARMIN_PASSWORD }}" -e TANITA_EMAIL="${{ secrets.TANITA_EMAIL }}" -e TANITA_PASSWORD="${{ secrets.TANITA_PASSWORD }}" mein-sync-tool
