name: Mein Tanita Garmin Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 6'

jobs:
  sync-job:
    runs-on: ubuntu-latest
    steps:
      - name: Code herunterladen
        uses: actions/checkout@v4
      
      - name: Go Umgebung laden
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          
      - name: Tresor-Daten in Config umwandeln
        run: |
          cat << 'EOF' > scaleconnect.yaml
          sync_task:
            from: "mytanita ${{ secrets.TANITA_EMAIL }} ${{ secrets.TANITA_PASSWORD }}"
            to: "garmin ${{ secrets.GARMIN_EMAIL }} ${{ secrets.GARMIN_PASSWORD }}"
          EOF
          
      - name: Synchronisation ausfuehren
        run: go run main.go
